// <auto-generated />
using System;
using Calculator.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Calculator.Persistence.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250121130457_AddContainers")]
    partial class AddContainers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Calculator.Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("InternetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("InternetAddress");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Calculator.Domain.Users.User", b =>
                {
                    b.OwnsMany("Calculator.Domain.Users.ValueObjects.Operation", "Operations", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Computation")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedInUtc")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Custom")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Result")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Value1")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Value2")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UserId", "Id");

                            b1.ToTable("Operation");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
